### ISSUE TITLE
Homework Checklist

### ISSUE THREAD

**Issue by JonMike8** [JonMike8/SSW345-Homework#1]
- [ ] Upload Github profile picture
- [ ] Submit Overleaf pdf
- [ ] Create Project teams and write prroject description
